<a href="https://colab.research.google.com/github/KateMals/Examples/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [14]:
from google.colab import files
uploaded = files.upload()

Saving diamonds.csv to diamonds (2).csv

In [15]:
dfD = pd.read_csv(open('diamonds.csv', 'rb'))
dfD.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [16]:
# 1 кол-во строк, 2 - кол-во столбцов
dfD.shape

(53940, 11)

In [18]:
# Посмотреть есть ли у нас пустые значения в данном случае пустых значений нет
dfD.isnull().sum()

Unnamed: 0    0
carat         0
cut           0
color         0
clarity       0
depth         0
table         0
price         0
x             0
y             0
z             0
dtype: int64

In [19]:
# Проверить тип данных в столбцах
dfD.dtypes

Unnamed: 0      int64
carat         float64
cut            object
color          object
clarity        object
depth         float64
table         float64
price           int64
x             float64
y             float64
z             float64
dtype: object

In [36]:
# Показать цену бриллиантов, каратность которых больше 4 карат
dfD.loc[dfD['carat'] > 4, ['price', 'carat']]

       price  carat
25998  15223   4.01
25999  15223   4.01
27130  17329   4.13
27415  18018   5.01
27630  18531   4.50

In [24]:
# Выбрать столбцы с ценой и цветом бриллианта
dfD[['price', 'color']]

       price color
0        326     E
1        326     E
2        327     E
3        334     I
4        335     J
...      ...   ...
53935   2757     D
53936   2757     D
53937   2757     D
53938   2757     H
53939   2757     D

[53940 rows x 2 columns]

In [26]:
# Максимальное значение цены
print(dfD['price'].max())
# Минимальное значение цены
print(dfD['price'].min())
# Среднее значение цены
print(dfD['price'].mean())
# Сумма цен
print(dfD['price'].sum())

18823
326
3932.799721913237
212135217

In [27]:
# Максимальное значение карата
print(dfD['carat'].max())
# Минимальное значение карата
print(dfD['carat'].min())
# Среднее значение карата
print(dfD['carat'].mean())
# Сумма карат
print(dfD['carat'].sum())

5.01
0.2
0.7979397478680014
43040.869999999995

In [29]:
# Общая картина
dfD.describe()

,Unnamed: 0,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,26970.500000,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,15571.281097,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,1.000000,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,13485.750000,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,26970.500000,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,40455.250000,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,53940.000000,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [34]:
# Определить цены при мин каратности
dfD.loc[dfD['carat'] == 0.2, ['price', 'carat']]

       price  carat
14       345    0.2
31591    367    0.2
31592    367    0.2
31593    367    0.2
31594    367    0.2
31595    367    0.2
31596    367    0.2
31597    367    0.2
31598    367    0.2
31599    367    0.2
31600    367    0.2
31601    367    0.2

In [37]:
# Определить цены при макс каратности
dfD.loc[dfD['carat'] == 5.01, ['price', 'carat']]

       price  carat
27415  18018   5.01

In [46]:
# Определить сколько бриллиантов можно приобрети с ценой меньше 350 долларов и выбрать самый большой для более выгодной покупки
dfD.loc[dfD['price'] < 350, ['price', 'carat', 'Unnamed: 0']]

    price  carat  Unnamed: 0
0     326   0.23           1
1     326   0.21           2
2     327   0.23           3
3     334   0.29           4
4     335   0.31           5
5     336   0.24           6
6     336   0.24           7
7     337   0.26           8
8     337   0.22           9
9     338   0.23          10
10    339   0.30          11
11    340   0.23          12
12    342   0.22          13
13    344   0.31          14
14    345   0.20          15
15    345   0.32          16
16    348   0.30          17

**В последнем задании получили 16 вариантов бриллиантов с ценой ниже 350 долларов (допустим у нас есть бюджет в 350 долларов всего и хочется купить самый крупный бриллиант за эти деньги). Самый выгодный в 15 строке выборки (0,32 карата).Он находится в изначальной таблице  и под номером 16 **